#ifndef TAIWAN_LOTTERY_STATUS_H
#define TAIWAN_LOTTERY_STATUS_H

/* Status codes returned by every int-returning C API. */
#define TAIWAN_LOTTERY_OK 0
#define TAIWAN_LOTTERY_NULL_PATH 1
#define TAIWAN_LOTTERY_INVALID_PATH_UTF8 2
#define TAIWAN_LOTTERY_IO_ERROR 3
#define TAIWAN_LOTTERY_NETWORK_ERROR 4
#define TAIWAN_LOTTERY_PARSE_ERROR 5
#define TAIWAN_LOTTERY_NULL_DATASET_CODE 6
#define TAIWAN_LOTTERY_INVALID_DATASET_CODE_UTF8 7
#define TAIWAN_LOTTERY_INVALID_GAME 8
#define TAIWAN_LOTTERY_INVALID_QUERY_UTF8 9
#define TAIWAN_LOTTERY_NULL_RESULT_POINTER 10
#define TAIWAN_LOTTERY_INVALID_LANGUAGE 11
#define TAIWAN_LOTTERY_INVALID_QUERY 12
/* An internal error (such as a caught panic) occurred; output pointers are left NULL. */
#define TAIWAN_LOTTERY_INTERNAL_ERROR 13

#endif
